### ISSUE TITLE
[SS13] Announcements are Repeated

### ISSUE THREAD

**Issue by N3X15** [N3X15/ss13-vox#6]
See:
* vgstation-coders/vgstation13#29445

**Comment by N3X15** [comment]
![image](https://user-images.githubusercontent.com/110073/118053952-4a3e3d00-b33a-11eb-9ea8-ffd6c255b1ff.png)

**Comment by JohnFulpWillard** [comment]
I'm compiling this right now and everything I put through it, is being said twice. Was this fixed?  I don't see any commits since this issue was closed...
